server:
  port: ${SERVER_PORT}

teams:
  service:
    url: ${TEAMS_SERVICE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sportpulse.ms_fixtures: DEBUG
    org.springframework.web: DEBUG
