server:
  port: ${SERVER_PORT}

teams:
  service:
    url: ${TEAMS_SERVICE_URL:http://localhost:9003}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
